### ISSUE TITLE
Troubles running the thing both inside and outside of Docker.

### ISSUE THREAD

**Issue by piotrf** [doino-gretchenliev/revolut-stocks#8]
Hello,

I have little experience with Python (JavaScript dev here) but I’m keen on porting this project to allow for calculations in Polish currency. I have to make this work first though, which I’m unable to.

A. When running `python stocks.py -i /Users/p/Playground/revolut-stocks/input -o /Users/p/Playground/revolut-stocks/output` I get:

```
  File "stocks.py", line 39
    logger.error(f"No statement files found.")
                                            ^
SyntaxError: invalid syntax
```

B. When running the thing inside of Docker I get:

```
revolut-stocks-calc_1  | [INFO]: Parsing statement files.
revolut-stocks-calc_1  | Traceback (most recent call last):
revolut-stocks-calc_1  |   File "stocks.py", line 76, in <module>
revolut-stocks-calc_1  |     main()
revolut-stocks-calc_1  |   File "stocks.py", line 45, in main
revolut-stocks-calc_1  |     statements = parse_statements(statement_files)
revolut-stocks-calc_1  |   File "/usr/src/stocks/libs/parser.py", line 121, in parse_statements
revolut-stocks-calc_1  |     activities = extract_activities(viewer)
revolut-stocks-calc_1  |   File "/usr/src/stocks/libs/parser.py", line 84, in extract_activities
revolut-stocks-calc_1  |     begin_index, end_index = get_activity_range(page_strings)
revolut-stocks-calc_1  |   File "/usr/src/stocks/libs/parser.py", line 29, in get_activity_range
revolut-stocks-calc_1  |     return begin_index + 1, end_index
revolut-stocks-calc_1  | TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
revolut-stocks_revolut-stocks-calc_1 exited with code 1
```

Any help will be much appreciated.

**Comment by doino-gretchenliev** [comment]
A. It seems there are no files in `/Users/p/Playground/revolut-stocks/input` or they are not accessible(permission problem).
B. The issue received in Docker is fixed in `master` branch now.

**Comment by piotrf** [comment]
Thank you for the prompt reply. Now:

A. I’m still getting that error even after changing permissions to both input and output folders 🤔 
B: Now I’m getting the following:

```
revolut-stocks-calc_1  | [INFO]: Parsing statement files.
revolut-stocks-calc_1  | Traceback (most recent call last):
revolut-stocks-calc_1  |   File "stocks.py", line 88, in <module>
revolut-stocks-calc_1  |     main()
revolut-stocks-calc_1  |   File "stocks.py", line 46, in main
revolut-stocks-calc_1  |     statements = parse_statements(statement_files)
revolut-stocks-calc_1  |   File "/usr/src/stocks/libs/parser.py", line 147, in parse_statements
revolut-stocks-calc_1  |     activities = extract_activities(viewer)
revolut-stocks-calc_1  |   File "/usr/src/stocks/libs/parser.py", line 112, in extract_activities
revolut-stocks-calc_1  |     activity = extract_activity(index - 3, page_strings, 6)
revolut-stocks-calc_1  |   File "/usr/src/stocks/libs/parser.py", line 69, in extract_activity
revolut-stocks-calc_1  |     end_index, symbol, symbol_description = extract_symbol_description(begin_index + 4, page_strings)
revolut-stocks-calc_1  |   File "/usr/src/stocks/libs/parser.py", line 60, in extract_symbol_description
revolut-stocks-calc_1  |     symbol = symbol_description[0 : symbol_description.index("-") - 1]
revolut-stocks-calc_1  | ValueError: substring not found
revolut-stocks_revolut-stocks-calc_1 exited with code 1
```

**Comment by jcovington16** [comment]
This error seems like the ValueError is thrown because of how you are indexing the array to find what you are looking for. Are you looking for that particular symbol? Does the symbol exist in the beginning, middle or end? I hope what I'm saying and asking is making sense. That error is only thrown when the substring isn't found in the string that you are searching for.

**Comment by doino-gretchenliev** [comment]
That error looks like an undiscovered bug in parsing. Can you activate the verbose login with `-v` flag. The log will then print the processing statements file and page where the issue is happening. After that, you can take a screenshot of the activities on that page and send it to me. Before sending the screenshot, please mask all sensitive information. You can reach me at doyno.gretchenliev@gmail.com.

**Comment by piotrf** [comment]
Thanks, about to send you that screenshot now.

**Comment by doino-gretchenliev** [comment]
@piotrf Please, confirm the parsing issues are fixed.

**Comment by piotrf** [comment]
Yes, can confirm that everything is now running smoothly.
